server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://registar.database.windows.net:1433;databaseName=registardb
    username: PostHeartAdmin1
    password: PostPass119!
    #make sure to change these to secret ones ^^^ maybe when I host the website I'll have to configure it to use environment variables
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
